### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by jmccusker** [PlummersSoftwareLLC/PongPCB#1]
Could you add a component parts list to this archive along with the links to the 3rd party parts you used to make this all work?   I'm going to try to do this and just want to be sure I have everything needed.  Great work Dave!

**Comment by davepl** [comment]
The video description has a list of the more interesting parts beyond supplies, as I don’t want to populate the GitHub with affiliate links!  Of course you need a Telstar console off eBay, but as long as the main chips work, the machine itself doesn’t need to…

- Dave

**Comment by jmccusker** [comment]
Thanks Dave,

I was mostly interested in the board parts like the resistors, caps,
sockets and connectors that fit the board.

I have a unit gathering dust and would love to duplicate what you did using
my spare parts.

Thanks,

Jim

**Comment by davepl** [comment]
I just used off the shelf resistors and caps, so don’t have part numbers for those!  But the schematic does detail everything you need to collect...

**Comment by jmccusker** [comment]
Thanks Dave,

I’ll take a look an post details of everything.  Thanks for doing this,
it’ll be a fun build for sure!

Jim

**Comment by rbergen** [comment]
I agree that it would be nice to include a list of the components that are required to complete the build. For one, I think it's quite easy to miss something if the bill of materials is deduced from the silk screen on the PCB. I also think that the list would be even more useful if we explicitly indicate which components can/must be taken from the Telstar console (I think the AY-3-8500 is the only one where "must" applies, but I may well be mistaken).

@jmccusker if I correctly understand your last comment as stating that you will put a list together then I'm happy to review it. I could also put one together myself this weekend, in which case a review by someone else would be helpful.

**Comment by jmccusker** [comment]
Rutger, if you have time this weekend to do it, then by all means please do
so.  I don't think I'll be able to get things pulled together for at least
another couple weeks given my schedule.  This is going to be a fun little
side-project for me and I plan to place it in my game room connected to a
big HDMI screen TV.  :-)  Should be great for some retro fun.

 --Jim

**Comment by rbergen** [comment]
I'll do my best, but no hard promises. There are some personal circumstances I won't bore you with that may make it not happen this weekend after all. I'll basically post the (draft) list as soon as I have it. Just to be clear: the list I create will indeed be based on reading the markings on the silk screen and some associated Googling. I don't have the hardware to put the project together available to me at the moment. In that sense the parts list will be "untested" until someone who built the project reviews it.

**Comment by jmccusker** [comment]
Sounds good.  I have the parts so I can validate things and help get us a validated list.  No rush, this is hobby work and should be fun.

**Comment by rbergen** [comment]
Don't worry, I'm not feeling rushed. I'm just managing expectations. :) I'll report back when I've put a first draft together.

**Comment by rbergen** [comment]
Below is a list of components that need to be installed onto the PCB, as taken from the PCB design. As Dave already indicated, a list of (other) components with affiliate links is available in the video description. That's also the reference I would make in the readme. The links in the table are to reference information only.

@davepl I initially took the oscillator type from the affiliate link in the video description (MCO-1510A), but that's a 4-pin component. The PCB only has through holes for 2. The HC49U is a two-pin component that also looks like what I see in the video. Can you confirm which of the two components is the correct one to use?

| Category | Value/type | Quantity | Board location(s) | Notes |
|-|-|-|-|-|
| Capacitor | 30pF | 2 | C1, C2 | |
| Capacitor | 0.1&#181;F | 2 | C3, C4 | |
| Crystal oscillator | HC49U 2.0MHz, or equivalent | 1 | Y1 | Oscillators are available in a wide range of frequencies, make sure to get the 2.0 MHz type! |
| DC barrel power connector | horizontal | 2 | J1, J4 | |
| IC | [AY-3-8500](https://en.wikipedia.org/wiki/AY-3-8500) | 1 | U1 | Has to be taken from the Coleco Telstar PCB, or another system that's based on it. If sockets are used, this IC must not be soldered but inserted into the socket after that has been soldered in. |
| IC | DIL-14 [4001](https://en.wikibooks.org/wiki/Practical_Electronics/IC/4001) | 1 | U3 | Can be taken from the Coleco Telstar PCB. If buying separately, note that a surface-mount version (SOIC-14) is also available that won't work for this build. If sockets are used, this IC must not be soldered but inserted into the socket after that has been soldered in. |
| IC | DIL-14 [4072](https://en.wikibooks.org/wiki/Practical_Electronics/IC/4072) | 1 | U2 | Can be taken from the Coleco Telstar PCB. If buying separately, note that a surface-mount version (SOIC-14) is also available that won't work for this build. If sockets are used, this IC must not be soldered but inserted into the socket after that has been soldered in. |
| Pin header | 2 pins | 1 | J5 | |
| Pin header | 14 pins | 1 | J2 | |
| RCA connector | RCJ-044 | 1 | J3 | |
| Resistor | 47&#8486; | 1 | R12 | |
| Resistor | 75&#8486; | 1 | R6 | |
| Resistor | 220&#8486; | 4 | R2, R5, R8, R9 | |
| Resistor | 330&#8486; | 1 | R10 | |
| Resistor | 510&#8486; | 2 | R3, R11 | |
| Resistor | 10K&#8486; | 2 | R4, R7 | |
| Resistor | 12M&#8486; | 1 | R1 | |
| Socket | 14 pins | 2 | U2, U3 | Use of sockets is recommended, but strictly speaking optional. |
| Socket | 28 pins | 1 | U1 | Use of sockets is recommended, but strictly speaking optional. |
| Transistor | [2N3904](https://en.wikipedia.org/wiki/2N3904) | 1 | Q1 | |

**Comment by davepl** [comment]
Thanks so much for putting this together!  If you’re OK with it, I’ll add it to the video description as well.  

The oscillator I could not find in stock anywhere, and wound up grabbing a pack of 10 off eBay.  I’m sure they must still be out there, but I couldn’t find a current 2MHz oscillator on Amazon.  Probably Digikey would be smarter :-)

- Dave

**Comment by rbergen** [comment]
You're welcome! Of course you can use it, but if you can give me a couple of minutes I will add a partslist.md to the repo that you can link to instead. I don't think the table format will survive if you try to paste it in the YouTube video description directly. I'll post another comment here with the URL in a few minutes.

About the oscillator, the main question I have is if I'm correct that it has to be a 2-pin oscillator?

**Comment by davepl** [comment]
Yup, just pasted the original in there and it’s a mess, but that might be unavoidable because I think the comments strips spaces!  Messy…

Yes, the oscillator is a 2-pin.  To be honest I don’t even know if a crystal is polarized or symmetrical, but I always put it in label up.

 -Dave

**Comment by rbergen** [comment]
The link to the parts list in a readable form is this: https://github.com/PlummersSoftwareLLC/PongPCB/blob/main/PARTSLIST.md

**Comment by rbergen** [comment]
Oh, and don't call me out on this if things do end up exploding, but I'm pretty sure 2-pin oscillators are not polarized. :)

**Comment by davepl** [comment]
Done!  Thanks again!

**Comment by jmccusker** [comment]
Well done Rutger!  I'm hoping to gather parts and get mine working again on my HDMI TV like Dave demonstrated.  Thanks!

**Comment by rbergen** [comment]
You are both very welcome! 

@jmccusker Please feel free to close this issue when you're sufficiently convinced that the point in question has been addressed.

**Comment by tpimh** [comment]
Hi @rbergen! In your part list, you mention that SOIC-14 parts won't work for this build. Is it due to mechanical incompatibilities (footprint being much smaller, thus the IC not fitting into the socket)? Or is there something more to it?

In the first case, I believe using an adapter [like this](https://www.cedist.com/products/pcb-smd-thru-hole-adapter-soic-14-dip-14) or even an [SMT socket](http://www.andksocket.com/sop-socket/SOP14-SOIC-14-SO14-to-DIP14-Pr.html) would solve the incompatibility.

**Comment by rbergen** [comment]
Hi @tpimh. SOIC-14 parts are surface-mount parts, and this is a through-hole build. Which is something I'm sure can be overcome one way or another, but that would then require additional parts. With a straightforward parts list like this, it's simply not realistic to consider all the permutations of components that don't fit but can be coerced into working using adapters, conversion sockets, etc. 

On another note, I'm going to close this issue as it's been stale for 4 months. If you want to continue this discussion, please open a topic in the Discussion section. I have just enabled that section specifically for that purpose.

Thanks!
